@echo Compiling Source Code...
javac VietCalendar.java -d compiled
@echo Creating JAR file...
jar --create --file VietCalendar.jar --manifest manifest.txt -0 -C compiled/ .
@echo Testing...
java -jar VietCalendar.jar
pause
